### ISSUE TITLE
Asset compilation

### ISSUE THREAD

**Issue by kyranb** [jarnovanleeuwen/laravel-dock#4]
First of all, not really an issue and I just wanted to thank you for sharing this repo.

For someone new to Kubernetes and docker it's been extremely helpful.

I just noticed that asset completion didn't seem to be covered within the build step. Not sure if that was an oversight or intentional.

**Comment by jarnovanleeuwen** [comment]
Nice to hear that the project has been helpful to you!

I haven't included asset compilation because the example routes I included do not require any asset compilation. I recommend adding this to your `Dockerfile` at the same location where `composer install` is being executed.

I am planning on refreshing this repository soon, upgrading dependencies and rewriting some parts as I have made some improvements in my other projects over the past two years.

**Comment by kyranb** [comment]
Makes sense 👍  

Thanks for the explanation and can't wait to see your updates :)

Have you had any experience with auto scaling the Laravel horizon process? If so, I'm curious what metric you used.

**Comment by jarnovanleeuwen** [comment]
I do have experience with Horizon's balancing strategies, but it is not really meaningful to say what strategy I am using because it really depends on the use case of the jobs and queues and of course your server environment. What I usually do is to go with the simplest (often the default) configuration and tune it only when necessary.

**Comment by kyranb** [comment]
With your implementation here, is there a way to tail the logs of the PHP process used for horizon?

Running

`kubectl logs -f deployment/queue --all-containers=true --since=1m`

outputs: 

```
Caching configuration...
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Compiled views cleared!
Blade templates cached successfully!
Starting Supervisor...
/usr/lib/python2.7/dist-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2020-11-12 00:45:30,489 INFO Included extra file "/etc/supervisor/conf.d/horizon.conf" during parsing
2020-11-12 00:45:30,489 INFO Set uid to user 1000 succeeded
2020-11-12 00:45:30,503 INFO RPC interface 'supervisor' initialized
2020-11-12 00:45:30,503 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-11-12 00:45:30,503 INFO supervisord started with pid 35
2020-11-12 00:45:31,505 INFO spawned: 'horizon_00' with pid 38
2020-11-12 00:45:32,715 INFO success: horizon_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

No stress if you're not sure 👍 Just thought I'd ask in case you knew :)

**Comment by jarnovanleeuwen** [comment]
I haven't done that so I am not entirely sure.. I use Horizon's web interface to monitor the handling of jobs.
